---
# tasks file for ansible-role-vim

- include: debian.yml
  when:
    ansible_os_family == "Debian"

- include: rhel.yml
  when:
    ansible_os_family == "RedHat"

- name: Copy over the required vimrc file
  get_url:
    url: "{{ vimrc_external_source }}"
    dest: "/home/{{ item }}/.vimrc"
  with_items:
    - "{{ vim_users }}"

# I personally use vundle to install plugins.
# https://github.com/VundleVim/Vundle.vim
- include: vundle.yml
